name: Build 🔧

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    # Get the code
    - uses: actions/checkout@v3
      with:
        submodules: true

    # Setup environment
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2


    - name: Lint 🌟
      run: terraform fmt --check --diff terraform/
    - name: Build 🔧
      run: echo "TODO..."
