name: Release 🚀

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true


    # Setup environment
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: '^1.16.4'
    - name: Install Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.101.0'
    - name: Install go-html-asset-manager
      run: |
        go install github.com/gauntface/go-html-asset-manager/v4/cmds/htmlassets@latest
        go install github.com/gauntface/go-html-asset-manager/v4/cmds/genimgs@latest
        go install github.com/tdewolff/minify/v2/cmd/minify@latest
    - name: Install NPM Deps
      run: npm install


    - name: Lint 🌟
      run: terraform fmt --check --diff terraform/


    # Configure AWS for genimgs and publish
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1
    - name: Gen Images
      run: genimgs


    # Build it
    - name: Build 🔧
      env:
        VIMEO_TOKEN: ${{ secrets.VIMEO_TOKEN }}
      run: npm run build


    # Deploy to AWS
    - name: Publish to AWS
      run: npx --package @gauntface/cli gauntface aws s3 deploy-static-site --directory="./public/" --bucket_name="www.gaunt.dev" --delete_exclude="generated/*"
      shell: bash
